"use strict";

// Square Payments capability (not yet wired for routing)
// Requires client-side tokenization (Web Payments SDK) to produce a sourceId/nonce.
// ENV per property via NODE_ENV using entries in Constants.squareLocationDetails.

import { Client, Environment, ApiError } from "square";
import * as Constants from "../constants";

// Helper to convert dollars to cents (integers)
const toCents = (amount) => {
    if (typeof amount === "number") return Math.round(amount * 100);
    const num = Number(amount);
    if (Number.isNaN(num)) throw { errormessage: "invalid amount", statusCode: 400 };
    return Math.round(num * 100);
};

// Simple idempotency key generator (no extra deps)
const makeIdemKey = () => `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

/**
 * Charge a card using Square Payments API.
 * NOTE: Expects a client-side generated Square token (sourceId/nonce). We do not accept raw PANs here.
 *
 * @param {Object} params
 * @param {("cw"|"sw"|"pp"|"TEST")} params.location
 * @param {string} params.squareSourceId - Square token/nonce from Web Payments SDK
 * @param {string} [params.squareVerificationToken] - Optional verification token if Strong Customer Authentication is used
 * @param {string} [params.first_name]
 * @param {string} [params.last_name]
 * @param {string} [params.email]
 * @param {string} [params.street]
 * @param {string} [params.city]
 * @param {string} [params.state]
 * @param {string} [params.zip]
 * @param {Array<{description:string, unitPrice:number, amount?:number, surcharge?:number}>} params.items
 * @param {number} params.total - in dollars
 * @param {string} params.tenantFirstName
 * @param {string} params.tenantLastName
 */
const chargeSquare = async ({
    location,
    squareSourceId,
    squareVerificationToken,
    first_name,
    last_name,
    email,
    street,
    city,
    state,
    zip,
    items,
    total,
    tenantFirstName,
    tenantLastName
}) => {
    // Validate presence of Square token first, so callers get a 400 even if env is misconfigured
    if (!squareSourceId) {
        // We intentionally do not accept raw card numbers here for PCI reasons.
        // The frontend must provide a Square token/nonce generated by Web Payments SDK.
        throw { errormessage: "missing Square payment token", statusCode: 400 };
    }

    const merchLocation = process.env.NODE_ENV === 'production' ? location : "TEST";
    const sqConfig = Constants.squareLocationDetails?.[merchLocation];
    if (!sqConfig?.accessToken || !sqConfig?.locationId) {
        throw { errormessage: `Square configuration missing for location ${merchLocation}`, statusCode: 500 };
    }

    const client = new Client({
        environment: process.env.NODE_ENV === 'production' ? Environment.Production : Environment.Sandbox,
        accessToken: sqConfig.accessToken
    });

    const idempotencyKey = makeIdemKey();

    // Create an Order with itemization
    const orderItems = (items || []).map((item) => ({
        name: item.description?.toString().slice(0, 255) || "Item",
        quantity: "1",
        basePriceMoney: {
            amount: BigInt(toCents(item.unitPrice)),
            currency: "USD"
        }
    }));

    const orderBody = {
        order: {
            locationId: sqConfig.locationId,
            referenceId: `${tenantFirstName || ''} ${tenantLastName || ''}`.trim() || undefined,
            lineItems: orderItems
        },
        idempotencyKey
    };

    // Create order first so we can attach it to the payment
    let orderId;
    try {
        const resp = await client.ordersApi.createOrder(orderBody);
        const result = resp?.result;
        orderId = result?.order?.id;
        if (!orderId) {
            throw { errormessage: "Square order error", statusCode: 400 };
        }
    } catch (e) {
        if (e && e.statusCode && e.errormessage) throw e;
        const errText = e instanceof ApiError ? (e.errors?.[0]?.detail || "Square order error") : (e?.message || "Square order error");
        throw { errormessage: errText, statusCode: 400 };
    }

    // Build buyer details
    const billingAddress = (first_name || last_name || street || city || state || zip) ? {
        addressLine1: street,
        locality: city,
        administrativeDistrictLevel1: state,
        postalCode: zip,
        country: "US"
    } : undefined;

    const buyerEmailAddress = email || undefined;

    // Amount for payment (total governs)
    const amountMoney = {
        amount: BigInt(toCents(total)),
        currency: "USD"
    };

    const paymentBody = {
        sourceId: squareSourceId,
        verificationToken: squareVerificationToken,
        idempotencyKey,
        amountMoney,
        locationId: sqConfig.locationId,
        orderId,
        autocomplete: true,
        note: `Payment for ${tenantFirstName || ''} ${tenantLastName || ''}`.trim(),
        buyerEmailAddress,
        billingAddress
    };

    if (process.env.NODE_ENV !== 'production') {
        const safeLogObj = { orderBody, paymentBody: { ...paymentBody, sourceId: "***" } };
        const replacer = (_k, v) => (typeof v === 'bigint' ? Number(v) : v);
        console.log(`${new Date().toISOString()} - Square payment request:`, JSON.stringify(safeLogObj, replacer, 2));
    }

    try {
        const { result } = await client.paymentsApi.createPayment(paymentBody);
        const payment = result?.payment;
        if (!payment) {
            throw { errormessage: "No payment response from Square", statusCode: 424 };
        }

        // Normalize to existing Authorize.Net-like response shape
        const normalized = {
            transactionResponse: {
                transId: payment.id,
                authCode: payment.approvalCode || undefined,
                accountType: payment.cardDetails?.card?.cardBrand,
                accountNumber: payment.cardDetails?.card?.last4 ? `XXXX${payment.cardDetails.card.last4}` : undefined
            },
            messages: {
                resultCode: payment.status === 'COMPLETED' ? 'OK' : payment.status || 'ERROR',
                message: [{ text: payment.status === 'COMPLETED' ? 'This transaction has been approved.' : `Status: ${payment.status}` }]
            }
        };
        return normalized;
    } catch (e) {
        if (e instanceof ApiError) {
            const err = e.errors?.[0];
            const detail = err?.detail || err?.code || "Square payment error";
            throw { errormessage: detail, statusCode: 400 };
        }
        throw { errormessage: e?.message || "Square payment error", statusCode: 400 };
    }
};

export default chargeSquare;
