"use strict";

// Square Payments capability (not yet wired for routing)
// Requires client-side tokenization (Web Payments SDK) to produce a sourceId/nonce.
// ENV per property via NODE_ENV using entries in Constants.squareLocationDetails.

import { Client, Environment, ApiError } from "square";
import * as Constants from "../constants";
import {debugLog} from "../util";

// Helper to convert dollars to cents (integers)
const toCents = (amount) => {
    if (typeof amount === "number") return Math.round(amount * 100);
    const num = Number(amount);
    if (Number.isNaN(num)) throw { errormessage: "invalid amount", statusCode: 400 };
    return Math.round(num * 100);
};

// Simple idempotency key generator (no extra deps)
const makeIdemKey = () => `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

/**
 * Charge a card using Square Payments API.
 * NOTE: Expects a client-side generated Square token (sourceId/nonce). We do not accept raw PANs here.
 *
 * @param {Object} params
 * @param {("cw"|"sw"|"pp"|"TEST")} params.location
 * @param {string} params.squareSourceId - Square token/nonce from Web Payments SDK
 * @param {string} [params.squareVerificationToken] - Optional verification token if Strong Customer Authentication is used
 * @param {string} [params.customerId] - Square customer ID to link payment to customer profile
 * @param {string} [params.first_name]
 * @param {string} [params.last_name]
 * @param {string} [params.email]
 * @param {string} [params.street]
 * @param {string} [params.city]
 * @param {string} [params.state]
 * @param {string} [params.zip]
 * @param {Array<{description:string, unitPrice:number, amount?:number, surcharge?:number}>} params.items
 * @param {number} params.total - in dollars
 * @param {string} params.tenantFirstName
 * @param {string} params.tenantLastName
 */
const chargeSquare = async ({
    location,
    squareSourceId,
    squareVerificationToken,
    customerId,
    first_name,
    last_name,
    email,
    street,
    city,
    state,
    zip,
    items,
    total,
    tenantFirstName,
    tenantLastName
}) => {
    // Validate presence of Square token first, so callers get a 400 even if env is misconfigured
    if (!squareSourceId) {
        // We intentionally do not accept raw card numbers here for PCI reasons.
        // The frontend must provide a Square token/nonce generated by Web Payments SDK.
        throw { errormessage: "missing Square payment token", statusCode: 400 };
    }

    const merchLocation = process.env.NODE_ENV === 'production' ? location : "TEST";
    const sqConfig = Constants.squareLocationDetails?.[merchLocation];
    if (!sqConfig?.accessToken || !sqConfig?.locationId) {
        throw { errormessage: `Square configuration missing for location ${merchLocation}`, statusCode: 500 };
    }

    const client = new Client({
        environment: process.env.NODE_ENV === 'production' ? Environment.Production : Environment.Sandbox,
        accessToken: sqConfig.accessToken
    });

    const idempotencyKey = makeIdemKey();

    // Create an Order with itemization
    const orderItems = (items || []).map((item) => ({
        name: item.description?.toString().slice(0, 255) || "Item",
        quantity: "1",
        basePriceMoney: {
            amount: BigInt(toCents(item.unitPrice)),
            currency: "USD"
        }
    }));

    const orderBody = {
        order: {
            locationId: sqConfig.locationId,
            referenceId: `${tenantFirstName || ''} ${tenantLastName || ''}`.trim() || undefined,
            lineItems: orderItems
        },
        idempotencyKey
    };

    // Create order first so we can attach it to the payment
    let orderId;
    try {
        const resp = await client.ordersApi.createOrder(orderBody);
        const result = resp?.result;
        orderId = result?.order?.id;
        if (!orderId) {
            throw { errormessage: "Square order error", statusCode: 400 };
        }
    } catch (e) {
        if (e && e.statusCode && e.errormessage) throw e;
        if (e instanceof ApiError) {
            const err = e.errors?.[0];
            // Use Square's detail text directly, or fall back to a generic message
            const detail = err?.detail || err?.code || "An error occurred while processing the order.";
            throw { errormessage: detail, statusCode: 400 };
        }
        throw { errormessage: e?.message || "An error occurred while processing the order.", statusCode: 400 };
    }

    // Build buyer details
    const billingAddress = (first_name || last_name || street || city || state || zip) ? {
        addressLine1: street,
        locality: city,
        administrativeDistrictLevel1: state,
        postalCode: zip,
        country: "US"
    } : undefined;

    const buyerEmailAddress = email || undefined;

    // Amount for payment (total governs)
    const amountMoney = {
        amount: BigInt(toCents(total)),
        currency: "USD"
    };

    const paymentBody = {
        sourceId: squareSourceId,
        verificationToken: squareVerificationToken,
        idempotencyKey,
        amountMoney,
        locationId: sqConfig.locationId,
        orderId,
        autocomplete: true,
        customerId: customerId, // Link payment to customer profile
        note: `Payment for ${tenantFirstName || ''} ${tenantLastName || ''}`.trim(),
        buyerEmailAddress,
        billingAddress
    };

    if (process.env.NODE_ENV !== 'production') {
        const safeLogObj = { orderBody, paymentBody: { ...paymentBody, sourceId: "***" } };
        const replacer = (_k, v) => (typeof v === 'bigint' ? Number(v) : v);
        debugLog(`${new Date().toISOString()} - Square payment request:`, JSON.stringify(safeLogObj, replacer, 2));
    }

    try {
        const { result } = await client.paymentsApi.createPayment(paymentBody);
        const payment = result?.payment;
        if (!payment) {
            throw { errormessage: "No payment response from Square", statusCode: 424 };
        }

        // Normalize to existing Authorize.Net-like response shape
        const normalized = {
            transactionResponse: {
                transId: payment.id,
                authCode: payment.approvalCode || undefined,
                accountType: payment.cardDetails?.card?.cardBrand,
                accountNumber: payment.cardDetails?.card?.last4 ? `XXXX${payment.cardDetails.card.last4}` : undefined
            },
            messages: {
                resultCode: payment.status === 'COMPLETED' ? 'OK' : payment.status || 'ERROR',
                message: [{ text: payment.status === 'COMPLETED' ? 'This transaction has been approved.' : `Status: ${payment.status}` }]
            }
        };
        return normalized;
    } catch (e) {
        // If error already has the expected format, re-throw as-is
        if (e && e.statusCode && e.errormessage) throw e;

        if (e instanceof ApiError) {
            const err = e.errors?.[0];

            // Use Square's detail text if available
            if (err?.detail) {
                throw { errormessage: err.detail, statusCode: 400 };
            }

            // If only code is available, provide a user-friendly message
            const code = err?.code;
            let friendlyMessage = "An error occurred while processing the payment.";

            // Map common codes to user-friendly messages
            const codeMessages = {
                'GENERIC_DECLINE': 'Your card was declined. Please try a different payment method or contact your card issuer.',
                'CARD_DECLINED': 'Your card was declined. Please try a different payment method or contact your card issuer.',
                'INSUFFICIENT_FUNDS': 'Your card has insufficient funds. Please try a different payment method.',
                'CARD_EXPIRED': 'Your card has expired. Please use a different card.',
                'INVALID_CARD': 'The card information is invalid. Please check your card details.',
                'INCORRECT_CVC': 'The card security code (CVV) is incorrect. Please check and try again.',
                'CVV_FAILURE': 'The card security code (CVV) verification failed. Please check and try again.',
                'INVALID_EXPIRATION': 'The card expiration date is invalid. Please check and try again.',
                'ADDRESS_VERIFICATION_FAILURE': 'The billing address could not be verified. Please check your address.',
                'PROCESSING_ERROR': 'An error occurred while processing your card. Please try again.',
                'FRAUDULENT': 'This transaction cannot be processed. Please contact your card issuer.',
                'CALL_ISSUER': 'Please contact your card issuer for authorization.',
                'PICKUP_CARD': 'This card cannot be used. Please contact your card issuer.',
                'CARD_NOT_SUPPORTED': 'This card type is not supported. Please use a different card.',
                'GATEWAY_TIMEOUT': 'The payment processing timed out. Please try again.',
                'TEMPORARY_ERROR': 'A temporary error occurred. Please try again in a moment.'
            };

            if (code && codeMessages[code]) {
                friendlyMessage = codeMessages[code];
            } else if (code) {
                // If we have a code but no mapping, provide a generic message with the code
                friendlyMessage = `The payment could not be processed. Please try a different payment method or contact support.`;
            }

            throw { errormessage: friendlyMessage, statusCode: 400 };
        }
        throw { errormessage: e?.message || "An error occurred while processing the payment.", statusCode: 400 };
    }
};

export default chargeSquare;
